{{- if .Values.monitoring.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.rancher.io'
    targetRevision: 101.0.0+up19.0.3
    helm:
      values: |
        prometheus:
          prometheusSpec:
            enableAdminAPI: true
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 750m
                memory: 750Mi
            retentionSize: 25GiB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                  - ReadWriteMany
                  resources:
                    requests:
                      storage: 20Gi
                  volumeMode: Filesystem
    chart: rancher-monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cattle-monitoring-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}