{{- if .Values.monitoring.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.rancher.io'
    targetRevision: 100.2.0+up40.1.2
    helm:
      values: |
        prometheus:
          prometheusSpec:
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 500Mi
    chart: rancher-monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cattle-monitoring-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}