{{- if .Values.monitoring.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.rancher.io'
    targetRevision: 100.2.0+up40.1.2
    chart: rancher-monitoring-crd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cattle-monitoring-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}